import { type NextPage } from "next";
import Head from "next/head";
import { LessonList } from "~/components/LessonList";
import { Main } from "~/components/Main";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>tango</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <LessonList />
      </Main>
    </>
  );
};

export default Home;
